hosts:
  staging:
    stage: staging
    hostname: silsomzorg.ssh.statik.be
    remote_user: silsomzorglivestatikbe
    deploy_path: ~/subsites/silsomzorg.staging.statik.be
    http_user: silsomzorglivestatikbe
    htaccess_file: htaccess-staging
    robots_file: robots-staging
    configFile: ~/.ssh/config
    http_host: silsomzorg.staging.statik.be
  production:
    stage: production
    hostname: silsomzorg.ssh.statik.be
    remote_user: silsomzorglivestatikbe
    deploy_path: ~/subsites/silsomzorg.live.statik.be
    http_user: silsomzorglivestatikbe
    htaccess_file: htaccess-production
    robots_file: robots-production
    configFile: ~/.ssh/config
    http_host: silsomzorg.live.statik.be
