field: 6d6fbd97-60e1-42ee-9eea-c007e8e2c129 # List
fieldLayouts:
  cabdc768-b25b-4723-95df-2996a79fb4ed:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9be5c0f5-81a2-4301-a7ee-7f616cd41325 # Block Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2467df9-bcd4-490e-9c0d-8f7b83faf4c9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 96603958-5229-412d-91e6-f54312d59d5d # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 383a76d0-d763-40a1-88e8-3567f558a48e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7f10f649-d7bf-4d67-b3be-60b5d08d9e8d
        userCondition: null
fields:
  9be5c0f5-81a2-4301-a7ee-7f616cd41325: # Block Title
    columnSuffix: voopfdpj
    contentColumnType: text
    fieldGroup: null
    handle: blockTitle
    instructions: null
    name: 'Block Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  96603958-5229-412d-91e6-f54312d59d5d: # Body
    columnSuffix: vbwwpdue
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: null
    name: Body
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      ckeConfig: 25f93ead-d3f6-4049-ba98-6378754f4289 # Extended
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: listItem
name: 'List Item'
sortOrder: 1
