fieldLayouts:
  21ba688e-2fe9-4413-b218-3539ce9cc83e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7d6fbbf5-5aca-4fda-9912-055b36b8333e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b5de6dcf-80e6-48e2-b846-0dab7f35c4c8 # Intro Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4607f71c-c40a-4969-a78d-40894f6b94bb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8ff8437a-a38f-47f0-b489-1701614eec3f # Header image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05b8c297-a0af-4536-9c03-54fe307af400
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6d6fbd97-60e1-42ee-9eea-c007e8e2c129 # List
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 621cfe0f-fed6-4dea-a7e9-ac0ca2085f3a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 56d715d0-6a9d-4562-9c66-e5b4caad7f44 # Content Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 17bf7592-88e3-4d18-8e0c-6a85f14f3fca
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8f477043-c74c-45a0-a8d1-6146f5579c66
        userCondition: null
handle: equitherapie
hasTitleField: true
name: Equitherapie
section: 30cf9f43-7f6c-41e2-8580-97a07eff970e # Equitherapie
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
