fieldLayouts:
  15592297-2447-4ddf-9a24-2490ec272ef7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c28a9c90-4ff2-4153-98c6-037eddae464f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b5de6dcf-80e6-48e2-b846-0dab7f35c4c8 # Intro Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eec2fcf2-94f7-44ff-bca0-f03dfb57a742
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8ff8437a-a38f-47f0-b489-1701614eec3f # Header image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57a28594-187f-4e9f-ac55-a97f37044c6e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 56d715d0-6a9d-4562-9c66-e5b4caad7f44 # Content Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef565278-d657-44c6-aaee-3a556ffd40b2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1671c383-d89b-4ce3-9f7f-ea6a3db2051d
        userCondition: null
handle: methode
hasTitleField: true
name: Methode
section: dae8fee4-9b79-4e5f-a186-788dca59dcbc # Methode
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
