fieldLayouts:
  e46b0731-05eb-4af7-b811-55b2320d6dbc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 38ec2a26-16fc-449f-a789-30629247d940
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6749ed1d-0ed0-4bf3-91f4-8e9ea127a657
        userCondition: null
handle: praktisch
hasTitleField: true
name: Praktisch
section: ae20f2da-b61a-4f2f-9f16-792256ed34f3 # Praktisch
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
