fieldLayouts:
  352fc9d6-f976-4b7d-a401-2c072f9687de:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6221c006-75b9-4fa5-a352-4cd4317fb5d7 # Youtube
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f100dce6-eb9a-41f4-8588-dfe4a029fd31
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f694fce1-48ca-4bfe-9fba-196195547a36 # Facebook
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 502c8a5c-50e4-4ac1-a0cb-a33276ce8b00
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ce1fab3c-0b02-49d8-8d8f-1bab2d7c05e2 # LinkedIn
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c48e5d6-1942-4008-b3bf-f3519317577c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9bc4b9f2-7fc6-48b0-a3df-8e9c061a70c6 # Instagram
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd4dec99-9eed-42b2-b17e-5d289a7b739f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2e4b3bb0-26e4-47d2-9445-54401a221c63 # X (Twitter)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 55c804e8-9016-460b-b51e-a14ae5eca9c3
            userCondition: null
            warning: null
            width: 100
        name: Socials
        uid: 4e4d2e41-d989-49cf-9859-c803407a540a
        userCondition: null
handle: socials
name: Socials
sortOrder: 2
